name: 'make-snapshot'
description: 'Make snapshot tarballs'
inputs:
  version:
    description: 'Target Version'
    required: false
  shallow-since:
    description: 'git fetch --shallow-since'
    required: true
    default: '2018-12-25 00:00:00'
  fetch-branch:
    description: 'fetch branch'
    required: false
  generate-tar-bz2:
    description: 'Generate .tar.bz2'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install libraries
      run: |
        set -x
        sudo apt-get update -q || :
        sudo apt-get install --no-install-recommends -q -y build-essential git bison autoconf ruby p7zip-full curl
      shell: bash
    - name: Checkout ruby/ruby for tool/make-snapshot
      run: git clone --single-branch --depth=1 --branch=debug_unexpected_rb_parser_ary_data_type https://github.com/yui-knk/ruby ruby
      shell: bash
    - name: Fetch branches and notes
      run: |
        set -x
        cd ruby
        git fetch --shallow-since='${{ inputs.shallow-since }}'
      shell: bash
    - name: Make snapshot
      run: |
        if [ -n "${{ inputs.generate-tar-bz2 }}" ]; then
          ruby ruby/tool/make-snapshot -archname=$archname -srcdir=ruby pkg ${{ inputs.version }}
        else
          ruby ruby/tool/make-snapshot -archname=$archname -srcdir=ruby -packages=gzip,xz,zip pkg ${{ inputs.version }}
        fi
      shell: bash
