# name: doxygen
# on:
#   schedule:
#     - cron: '30 2,5,8,11,14,17,20,23 * * *' # Every three hours
#   repository_dispatch:
#     types: "doxygen"

# jobs:
#   latest:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Install libraries
#         run: |
#           set -x
#           sudo sed /etc/apt/sources.list -e "s/^# deb-src/deb-src/g" -i
#           sudo apt-get update -q || :
#           sudo apt-get install --no-install-recommends -q -y ruby doxygen graphviz
#           sudo apt-get build-dep -q -y ruby$(ruby -e 'puts File.basename(RUBY_VERSION, ".*")')

#       - name: Checkout ruby/ruby
#         run: |
#           git clone --depth=1 https://github.com/ruby/ruby .
#           git rev-parse HEAD
#           git log

#       - run: ./autogen.sh
#       - run: ./configure
#       - run: make Doxyfile
#       - run: doxygen
#       - uses: actions/upload-artifact@v4
#         with:
#           name: doxygen-latest-html
#           path: doc/capi/html
#       - name: Upload results
#         run: |
#           aws s3 sync doc/capi/html/ s3://rubyci/doxygen-latest-html --no-progress
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.RUBYCI_AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.RUBYCI_AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: us-west-2
